// Авторизация
export const SET_USER_DATA = 'SET_USER_DATA';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';

// Запрос реестра банков
// get
export const BANKS_GET_REQUEST = 'BANKS_GET_REQUEST';
export const BANKS_GET_SUCCESS = 'BANKS_GET_SUCCESS';
export const BANKS_GET_ERROR = 'BANKS_GET_ERROR';
// delete
export const BANK_DELETE_REQUEST = 'BANK_DELETE_REQUEST';
export const BANK_DELETE_SUCCESS = 'BANK_DELETE_SUCCESS';
export const BANK_DELETE_ERROR = 'BANK_DELETE_ERROR';
// post
export const BANK_POST_REQUEST = 'BANK_POST_REQUEST';
export const BANK_POST_SUCCESS = 'BANK_POST_SUCCESS';
export const BANK_POST_ERROR = 'BANK_POST_ERROR';
// put
export const BANK_PUT_REQUEST = 'BANK_PUT_REQUEST';
export const BANK_PUT_SUCCESS = 'BANK_PUT_SUCCESS';
export const BANK_PUT_ERROR = 'BANK_PUT_ERROR';

// Запрос реестра социальных групп
export const SOCIALGROUPS_GET_REQUEST = 'SOCIALGROUPS_GET_REQUEST';
export const SOCIALGROUPS_GET_SUCCESS = 'SOCIALGROUPS_GET_SUCCESS';
export const SOCIALGROUPS_GET_ERROR = 'SOCIALGROUPS_GET_ERROR';

// Запрос реестра Прожиточного минимума
export const LIVINGWAGES_GET_REQUEST = 'LIVINGWAGES_GET_REQUEST';
export const LIVINGWAGES_GET_SUCCESS = 'LIVINGWAGES_GET_SUCCESS';
export const LIVINGWAGES_GET_ERROR = 'LIVINGWAGES_GET_ERROR';

// Запрос сотрудников
export const EMPLOYESS_GET_REQUEST = 'EMPLOYESS_GET_REQUEST';
export const EMPLOYESS_GET_SUCCESS = 'EMPLOYESS_GET_SUCCESS';
export const EMPLOYESS_GET_ERROR = 'EMPLOYESS_GET_ERROR';

// Раскрытие сайдбара
export const SIDEBAR_BURGER_CLICK = 'SIDEBAR_BURGER_CLICK';
