// Авторизация
export const SET_USER_DATA = 'SET_USER_DATA';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';

// Запрос реестра банков

export const BANKS_GET_REQUEST = 'BANKS_GET_REQUEST';
export const BANKS_GET_SUCCESS = 'BANKS_GET_SUCCESS';
export const BANKS_GET_ERROR = 'BANKS_GET_ERROR';

export const BANK_DELETE_REQUEST = 'BANK_DELETE_REQUEST';
export const BANK_DELETE_SUCCESS = 'BANK_DELETE_SUCCESS';
export const BANK_DELETE_ERROR = 'BANK_DELETE_ERROR';

export const BANK_POST_REQUEST = 'BANK_POST_REQUEST';
export const BANK_POST_SUCCESS = 'BANK_POST_SUCCESS';
export const BANK_POST_ERROR = 'BANK_POST_ERROR';

export const BANK_PUT_REQUEST = 'BANK_PUT_REQUEST';
export const BANK_PUT_SUCCESS = 'BANK_PUT_SUCCESS';
export const BANK_PUT_ERROR = 'BANK_PUT_ERROR';
//----------------------

// Запрос реестра должностей

export const JOBPOSITIONS_GET_REQUEST = 'JOBPOSITIONS_GET_REQUEST';
export const JOBPOSITIONS_GET_SUCCESS = 'JOBPOSITIONS_GET_SUCCESS';
export const JOBPOSITIONS_GET_ERROR = 'JOBPOSITIONS_GET_ERROR';

export const JOBPOSITION_DELETE_REQUEST = 'JOBPOSITION_DELETE_REQUEST';
export const JOBPOSITION_DELETE_SUCCESS = 'JOBPOSITION_DELETE_SUCCESS';
export const JOBPOSITION_DELETE_ERROR = 'JOBPOSITION_DELETE_ERROR';

export const JOBPOSITION_POST_REQUEST = 'JOBPOSITION_POST_REQUEST';
export const JOBPOSITION_POST_SUCCESS = 'JOBPOSITION_POST_SUCCESS';
export const JOBPOSITION_POST_ERROR = 'JOBPOSITION_POST_ERROR';

export const JOBPOSITION_PUT_REQUEST = 'JOBPOSITION_PUT_REQUEST';
export const JOBPOSITION_PUT_SUCCESS = 'JOBPOSITION_PUT_SUCCESS';
export const JOBPOSITION_PUT_ERROR = 'JOBPOSITION_PUT_ERROR';

//-------------------------

// Запрос реестра ролей

export const ROLES_GET_REQUEST = 'ROLES_GET_REQUEST';
export const ROLES_GET_SUCCESS = 'ROLES_GET_SUCCESS';
export const ROLES_GET_ERROR = 'ROLES_GET_ERROR';

export const ROLE_DELETE_REQUEST = 'ROLE_DELETE_REQUEST';
export const ROLE_DELETE_SUCCESS = 'ROLE_DELETE_SUCCESS';
export const ROLE_DELETE_ERROR = 'ROLE_DELETE_ERROR';

export const ROLE_POST_REQUEST = 'ROLE_POST_REQUEST';
export const ROLE_POST_SUCCESS = 'ROLE_POST_SUCCESS';
export const ROLE_POST_ERROR = 'ROLE_POST_ERROR';

export const ROLE_PUT_REQUEST = 'ROLE_PUT_REQUEST';
export const ROLE_PUT_SUCCESS = 'ROLE_PUT_SUCCESS';
export const ROLE_PUT_ERROR = 'ROLE_PUT_ERROR';

//-------------------------

// Запрос реестра организованной структуры

export const ORGSTRUCTURES_GET_REQUEST = 'ORGSTRUCTURES_GET_REQUEST';
export const ORGSTRUCTURES_GET_SUCCESS = 'ORGSTRUCTURES_GET_SUCCESS';
export const ORGSTRUCTURES_GET_ERROR = 'ORGSTRUCTURES_GET_ERROR';

export const ORGSTRUCTURE_DELETE_REQUEST = 'ORGSTRUCTURE_DELETE_REQUEST';
export const ORGSTRUCTURE_DELETE_SUCCESS = 'ORGSTRUCTURE_DELETE_SUCCESS';
export const ORGSTRUCTURE_DELETE_ERROR = 'ORGSTRUCTURE_DELETE_ERROR';

export const ORGSTRUCTURE_POST_REQUEST = 'ORGSTRUCTURE_POST_REQUEST';
export const ORGSTRUCTURE_POST_SUCCESS = 'ORGSTRUCTURE_POST_SUCCESS';
export const ORGSTRUCTURE_POST_ERROR = 'ORGSTRUCTURE_POST_ERROR';

export const ORGSTRUCTURE_PUT_REQUEST = 'ORGSTRUCTURE_PUT_REQUEST';
export const ORGSTRUCTURE_PUT_SUCCESS = 'ORGSTRUCTURE_PUT_SUCCESS';
export const ORGSTRUCTURE_PUT_ERROR = 'ORGSTRUCTURE_PUT_ERROR';

//-------------------------

// Запрос реестра максимальная доля расходов

export const MAXCOSTS_GET_REQUEST = 'MAXCOSTS_GET_REQUEST';
export const MAXCOSTS_GET_SUCCESS = 'MAXCOSTS_GET_SUCCESS';
export const MAXCOSTS_GET_ERROR = 'MAXCOSTS_GET_ERROR';

export const MAXCOST_DELETE_REQUEST = 'MAXCOST_DELETE_REQUEST';
export const MAXCOST_DELETE_SUCCESS = 'MAXCOST_DELETE_SUCCESS';
export const MAXCOST_DELETE_ERROR = 'MAXCOST_DELETE_ERROR';

export const MAXCOST_POST_REQUEST = 'MAXCOST_POST_REQUEST';
export const MAXCOST_POST_SUCCESS = 'MAXCOST_POST_SUCCESS';
export const MAXCOST_POST_ERROR = 'MAXCOST_POST_ERROR';

export const MAXCOST_PUT_REQUEST = 'MAXCOST_PUT_REQUEST';
export const MAXCOST_PUT_SUCCESS = 'MAXCOST_PUT_SUCCESS';
export const MAXCOST_PUT_ERROR = 'MAXCOST_PUT_ERROR';

//-------------------------

// Запрос реестра отношений

export const RELATIONS_GET_REQUEST = 'RELATIONS_GET_REQUEST';
export const RELATIONS_GET_SUCCESS = 'RELATIONS_GET_SUCCESS';
export const RELATIONS_GET_ERROR = 'RELATIONS_GET_ERROR';

export const RELATION_DELETE_REQUEST = 'RELATION_DELETE_REQUEST';
export const RELATION_DELETE_SUCCESS = 'RELATION_DELETE_SUCCESS';
export const RELATION_DELETE_ERROR = 'RELATION_DELETE_ERROR';

export const RELATION_POST_REQUEST = 'RELATION_POST_REQUEST';
export const RELATION_POST_SUCCESS = 'RELATION_POST_SUCCESS';
export const RELATION_POST_ERROR = 'RELATION_POST_ERROR';

export const RELATION_PUT_REQUEST = 'RELATION_PUT_REQUEST';
export const RELATION_PUT_SUCCESS = 'RELATION_PUT_SUCCESS';
export const RELATION_PUT_ERROR = 'RELATION_PUT_ERROR';

//-------------------------

// Запрос реестра социальных групп
export const SOCIALGROUPS_GET_REQUEST = 'SOCIALGROUPS_GET_REQUEST';
export const SOCIALGROUPS_GET_SUCCESS = 'SOCIALGROUPS_GET_SUCCESS';
export const SOCIALGROUPS_GET_ERROR = 'SOCIALGROUPS_GET_ERROR';

// Запрос реестра Прожиточного минимума
export const LIVINGWAGES_GET_REQUEST = 'LIVINGWAGES_GET_REQUEST';
export const LIVINGWAGES_GET_SUCCESS = 'LIVINGWAGES_GET_SUCCESS';
export const LIVINGWAGES_GET_ERROR = 'LIVINGWAGES_GET_ERROR';

// Запрос сотрудников
export const EMPLOYESS_GET_REQUEST = 'EMPLOYESS_GET_REQUEST';
export const EMPLOYESS_GET_SUCCESS = 'EMPLOYESS_GET_SUCCESS';
export const EMPLOYESS_GET_ERROR = 'EMPLOYESS_GET_ERROR';

// Раскрытие сайдбара
export const SIDEBAR_BURGER_CLICK = 'SIDEBAR_BURGER_CLICK';
